import Head from "next/head";
import React from "react";

export default function Signup() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10">
        <div className="flex flex-row">
          <div className="flex-1">
            <form>
              <div className="form-group">
                <label htmlFor="username">Username:</label>
                <input type="text" id="username" name="username" />
              </div>

              <div className="form-group">
                <label htmlFor="email">Password:</label>
                <input type="password" id="password" name="password" />
              </div>

              <div className="form-group">
                <input type="submit" value="Login" className="btn btn-default btn-ghost" />
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  )
}
