import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'
import board from '../styles/Board.module.css'

function Grid({ grid, onClick }) {
  return <span onClick={onClick} className={board.grid}>{grid?.mark || "·"}</span>
}

export default function Home({ data }) {
  useEffect(() => {
    console.log(data)
  }, []);

  const onGridClick = async (xpos: number, ypos: number) => {
    console.log({ xpos, ypos })
    return await fetch(`http://aloi:3000/game/3`, {
      method: "POST",
      body: JSON.stringify({
        xpos, ypos, playerId: 1
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    }).then(response => response.json())
  }

  const rows = data.board.map((grids: Array<{ grid: { xpos: number, ypos: number } }>, i) => {
    const _grids = grids.map(
      (g, ii) => <Grid key={ii} grid={g} onClick={() => onGridClick(g.grid.xpos, g.grid.ypos)} />
    )
    return <div key={i} className={styles.grid}>{_grids}</div>
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <pre style={{ "font-size": "2em" }}>
          {rows}
        </pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  // const data = await fetch('http://aloi:3000/game/3').then(res => res.json())
  const data = {}
  console.log("aaaaaaa", { data })

  return { props: { data }}
}
